# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-5314cf22-8ffb-4296-a253-7d1b2ac06f78";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5314cf22-8ffb-4296-a253-7d1b2ac06f78".device = "/dev/disk/by-uuid/5314cf22-8ffb-4296-a253-7d1b2ac06f78";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/65C7-B71F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-fc4e4f22-93a9-49cc-9f91-f0b3a33d754d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
