# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-b11d5383-0601-440f-b099-d06b29c69b90";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b11d5383-0601-440f-b099-d06b29c69b90".device = "/dev/disk/by-uuid/b11d5383-0601-440f-b099-d06b29c69b90";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6199-C636";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-1b6dba1b-4b4a-409f-9d42-ada81e59e176"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
